version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  hello:
    cmds:
      - echo "Bonjour à vous mes très chers amis !"
  update:
    cmds:
      - git pull
      - git -C ../config/ pull
      - sudo rm -r /var/www/beta 
      - sudo rm -r /var/www/front
      - sudo cp -r release_front/beta/dist /var/www/beta
      - sudo cp -r release_front/default/dist /var/www/front 
      - sudo nixos-rebuild switch
  log_keycloak:
    cmds:
      - journalctl -u keycloak -e
  import_database:
    cmds:
      - pg_restore -h <host> -p <port> -U <db_user_name> -d databasename -c data_base_dump
  ssh_add:
    cmds:
      - eval `ssh-agent -s` && ssh-add ~/.ssh/erica_epona